
library(devtools)
suppressMessages(load_all("/home/noshadh/Desktop/TPO/tpo6/tpo/rlibs/cnvex"))

library(gridExtra)
library(ggpubr)
library(rtracklayer)
library(matrixStats)
library(Rsamtools)
library(BSgenome.Hsapiens.UCSC.hg38)
library(GenomeInfoDb)
library(GenomicRanges)
library(S4Vectors)
library(IRanges)
library(data.table )
library(stringr)
library(Biostrings)
library(VariantAnnotation)
library(limma)
library(DNAcopy)
library(DelayedArray)
library(jointseg)
library(raster)
library(robfilter)
library(fastICA)
library(MASS)
library(foreach)
library(parallel)
library(doParallel)